# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MoviesStore
  pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'
  pod "MBCircularProgressBar"

  target 'MoviesStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesStoreUITests' do
    # Pods for testing
  end

end
